[package]
name = "idsbot"
version = "0.1.0"
authors = ["Ian D. Scott <ian@perebruin.com>"]

[dependencies]
hyper = "0.9"
serde_json = "0.7"
regex = "0.1"
irc = "0.11"
xdg-basedir = "1.0"
url = "1.1"
lazy_static = "0.2"
