[package]
name = "github-bot"
version = "0.1.0"
authors = ["Ian D. Scott <ian@perebruin.com>"]

[dependencies]
hyper = "0.6.10"
serde_json = "0.5"
regex = "0.1.41"
irc = "0.9.0"
xdg-basedir = "0.2.2"
